nelmio_api_doc:
    documentation:
        info:
            title: Winedows API
            description: API description
#            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []

    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api
                - ^/api(?!/doc$)
            name_patterns: [ ^api_ ]
#        v2:
#            path_patterns: [ ^/api/v2 ]
#            name_patterns: [ ^api_v2 ]
#        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
