# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    import_files_directory: '%kernel.project_dir%/import'
    event_pics_subdirectory: 'events'
    vendor_logo_subdirectory: 'vendor/logos'
    vendor_pics_subdirectory: 'vendor/pics'
    product_pics_subdirectory: 'products'
    mailer_sender_email: '%env(MAILER_SENDER_EMAIL)%'
    mailer_send_confirm_email: '%env(MAILER_SEND_CONFIRM_REGISTER)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    App\Service\FileUploader:
        arguments:
            $uploadsDirectory: '%uploads_directory%'
            $importFilesDirectory: '%import_files_directory%'
            $productPicsSubDirectory: '%product_pics_subdirectory%'
            $vendorLogoSubDirectory: '%vendor_logo_subdirectory%'
            $vendorPicsSubDirectory: '%vendor_pics_subdirectory%'
            $eventPicsSubDirectory: '%event_pics_subdirectory%'

sirian_suggest:
    form_options:
        widget: select2_v4
        attr:
            placeholder: "Search..."
            width: '100%'
    orm:
        product:
            class: "App:Product"
            property: summary
            search:
                name: ~
        appellation:
            class: "App:Appellation"
            property: summary
            search:
                name: ~
